# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OYrvP3PNr6G-pI-YlHttdOvCVIxl7WIe
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as

df = pd.read_csv("/content/Iris Dataset.csv")

from google.colab import files
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

uploaded = files.upload()
df = pd.read_csv("Iris Dataset.csv")

plt.figure(figsize=(8, 6))
sns.barplot(x="Species", y="SepalLengthCm", data=df)
plt.title("Barplot of Sepal Length across Species")

plt.figure(figsize=(8, 6))
sns.countplot(x="Species", data=df)
plt.title("Count of Each Species")

plt.figure(figsize=(8, 6))
sns.boxplot(x="Species", y="SepalWidthCm", data=df)
plt.title("Boxplot of Sepal Width across Species")

plt.figure(figsize=(8, 6))
sns.swarmplot(x="Species", y="SepalWidthCm", data=df)
plt.title("Swarm Plot of Sepal Width across Species")

plt.figure(figsize=(8, 6))
sns.histplot(df["SepalWidthCm"], kde=True)
plt.title("Distribution of Sepal Width")

sns.jointplot(x="SepalWidthCm", y="SepalLengthCm", data=df, kind="scatter")

sns.pairplot(df, hue="Species")