# -*- coding: utf-8 -*-
"""Weather Data Visualization

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YPt_c9vNoHi6S4MyazK4-uCddLxQjZEn
"""

import pandas as pd
import seaborn as sns
#sns.set(color_codes=True)

from google.colab import files
Files= files.upload()

weather = pd.read_csv("Weather Dataset - Trial Activity DataSet.csv.csv")

weather.head()

weather.info()

sns.barplot(weather['wind_speed'])

sns.barplot(weather['temperature'])

sns.distplot(weather['temperature'])

sns.distplot(weather['humidity'], rug=True);

sns.jointplot(weather['humidity'])

sns.jointplot(weather['temperature'])

sns.jointplot(weather['humidity'], kind="hex")

sns.jointplot(weather['temperature'], kind="hex")

sns.jointplot(weather['temperature'], kind="kde")

sns.jointplot(weather['humidity'], kind="kde")

sns.pairplot(weather[['temperature']])

sns.pairplot(weather[['humidity']])

sns.pairplot(weather[['air_pollution_index']])

sns.stripplot(weather[['temperature']])

sns.stripplot(weather[['weather_type']], jitter = True)

sns.swarmplot(weather[['temperature']])

sns.swarmplot(weather[['humidity']])

sns.boxplot(weather[['temperature']])

sns.boxplot(weather[['humidity']])

sns.boxplot(weather[['weather_type']])

sns.countplot(weather[['weather_type']])

sns.pointplot(weather[['temperature']])

sns.pointplot(weather[['humidity']])

sns.pointplot(weather[['weather_type']])

sns.lmplot(x="humidity", y="temperature", data=weather)

sns.lmplot(x="humidity", y="temperature", hue="weather_type", data=weather)